src/DotnetSpider.Portal/Controllers/AgentController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotnetSpider.Portal.Controllers
{
	[Route("agents")]
	public class AgentController : Controller
	{
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpGet("{id}/heartbeats")]
		public IActionResult Heartbeat()
		{
			return View();
		}
	}
}

src/DotnetSpider.Portal/Controllers/SpiderController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotnetSpider.Portal.Controllers
{
	[Route("spiders")]
	public class SpiderController
		: Controller
	{
		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpGet("{id}/histories")]
		public IActionResult History()
		{
			return View();
		}
	}
}

src/DotnetSpider.Portal/Views/Shared/Pagination.cshtml
<script type="text/x-template" id="pagination-template">
    <ul class="pagination">
        <!-- prev -->
        <li
            :class="['page-item', {'disabled' : disablePre}]"
            v-on:click="prev">
            <a class="page-link" href="#">Previous</a>
        </li>
        <!-- first -->
        <li
            :class="['page-item', {'disabled' : disableFirst}]"
            v-on:click="first">
            <a class="page-link" href="#">First</a>
        </li>
        <li
            v-for="pager in pagers"
            :class="['page-item', {'active' : page == pager}]"
            v-on:click="go(pager)">
            <a class="page-link" href="#">{{ pager }}</a>
        </li>
        <!-- last -->
        <li
            :class="['page-item', {'disabled' : disableLast}]"
            v-on:click="last">
            <a class="page-link" href="#">Last</a>
        </li>
        <!-- next -->
        <li
            :class="['page-item', {'disabled' : disableNext}]"
            v-on:click="next">
            <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</script>

<environment names="Development">
    <script src="~/js/pagination.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/pagination.min.js" asp-append-version="true"></script>
</environment>

src/DotnetSpider.Portal/Views/Shared/Select2.cshtml
<script type="text/x-template" id="select2-template">
    <select>
        <slot></slot>
  </select>
</script>

<environment names="Development">
    <script src="~/js/select2.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/select2.min.js" asp-append-version="true"></script>
</environment>

src/DotnetSpider.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Spider Admin</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/sweetalert.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/icheck-bootstrap/icheck-bootstrap.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/sweetalert.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/icheck-bootstrap/icheck-bootstrap.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
    @RenderSection("Styles", false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spider Admin</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a> *@
                    @* </li> *@
                    <li class="nav-item margin-left-10">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Agent" asp-action="Index">Agent</a>
                    </li>
                    <li class="nav-item margin-left-10">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Spider" asp-action="Index">Spider</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3" id="app">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - DotnetSpider
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
<script src="~/js/sweetalert.js" asp-append-version="true"></script>
<script src="~/lib/select2/dist/js/select2.full.min.js" asp-append-version="true"></script>
<script src="~/lib/vue/dist/vue.min.js" asp-append-version="true"></script>
<environment names="Development">
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
@await Html.PartialAsync("Pagination")
@await Html.PartialAsync("Select2")
@RenderSection("Scripts", false)
</body>
</html>

src/DotnetSpider.Portal/Views/Shared/_SideBar.cshtml
<!-- Sidebar Menu -->
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER @DateTimeOffset.Now.ToString("yyyy/MM/dd HH:mm:ss")</li>
    <li class="active menu" id="MenuHome">
        <a href="/">
            <i class="fa fa-area-chart"></i><span>Home</span>
        </a>
    </li>
    <li id="MenuRepository" class="menu">
        <a href="/docker-repository">
            <i class="fa fa-database"></i><span>Repository</span>
        </a>
    </li>
    <li id="MenuSpider" class="menu">
        <a href="/spider">
            <i class="fa fa-calendar"></i><span>Spider</span>
        </a>
    </li>
    <li id="MenuDownloaderAgent" class="menu">
        <a href="/agent">
            <i class="fa fa-desktop"></i><span>Agent</span>
        </a>
    </li>
</ul>
<!-- /.sidebar-menu -->